workflows:
  ionic-capacitor-ios-workflow-optimized:
    name: Capacitor iOS Workflow (Optimized)
    max_build_duration: 60
    environment:
      node: latest
      cache:
        - node_modules
        - ~/.bun
        - ios/App/Pods
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Install optimized dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          echo "Installing only used dependencies..."
          bun install --silent
      - name: Build web assets
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          echo "Building web assets..."
          bun run build
      - name: Generate iOS project
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          echo "Generating iOS project with minimal plugins..."
          npx cap add ios --no-deps
          npx cap sync ios --no-build
      - name: Build iOS app (optimized)
        script: |
          cd ios/App
          echo "Installing minimal CocoaPods..."
          pod install --silent --repo-update
          echo "Building iOS app with only used plugins..."
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,id=FD1BF54E-4D3D-45B8-AF09-425C68025542' -derivedDataPath build -quiet -parallelizeTargets
      - name: Create iOS bundle
        script: |
          cd ios/App/build/Build/Products/Debug-iphonesimulator
          echo "Creating optimized iOS bundle..."
          zip -r ../../../../../../ios-app-optimized.zip App.app -q
          echo "✅ Optimized iOS build completed!"
    artifacts:
      - ios-app-optimized.zip
