workflows:
  ionic-capacitor-ios-ipa:
    name: Capacitor iOS IPA
    max_build_duration: 60
    environment:
      node: latest
      ios_signing: # <‑‑ lets Codemagic fetch the right files
        distribution_type: app_store # or ad_hoc / development
        bundle_identifier: com.demo.app # keep in sync with capacitor.config.ts
      groups:
        - ios_credentials # the group that holds your p12 & profile
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Install deps & build web
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install --silent
          bun run build
      - name: Generate iOS project
        script: |
          npx cap add ios 
          npx cap sync ios

      # 3. **Let Codemagic wire the provisioning profiles into the Xcode project**
      - name: Set up code signing settings
        script: xcode-project use-profiles

      # 4. **Archive _and_ export the IPA in one shot**
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-flags="-destination 'generic/platform=iOS'" \
            --export-options-plist "/Users/builder/export_options.plist"  # auto‑generated

    # 5. **Expose the IPA (and dSYMs) as build artifacts**
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
