workflows:
  ionic-capacitor-ios-workflow-optimized:
    name: Capacitor iOS Workflow (Optimized)
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Install optimized dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          echo "Installing only used dependencies..."
          bun install --silent
      - name: Build web assets
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          echo "Building web assets..."
          bun run build
      - name: Generate iOS project
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          echo "Generating iOS project with minimal plugins..."
          npx cap add ios
          npx cap sync ios
      - name: Build iOS app (archive)
        script: |
          cd ios/App
          echo "Archiving iOS app for device..."
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath $PWD/build/App.xcarchive -destination 'generic/platform=iOS' archive
      - name: Export .ipa
        script: |
          cd ios/App
          echo "Exporting .ipa..."
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportPath $PWD/build/ipa -exportOptionsPlist ExportOptions.plist
      - name: Create iOS bundle
        script: |
          cd ios/App/build/Build/Products/Debug-iphonesimulator
          echo "Creating optimized iOS bundle..."
          zip -r ../../../../../../ios-app-optimized.zip App.app -q
          echo "✅ Optimized iOS build completed!"
    artifacts:
      - ios/App/build/ipa/*.ipa
